# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --substitutions _REGION='<region>'
steps:
#  - name: 'gcr.io/${PROJECT_ID}/terraform:0.12.8'
#    dir: './terraform/dns-zone'
#    args: [
#      'init',
#      '-backend-config=bucket=${_PROJECT_ID}-${_DNS_ZONE_NAME}'
#    ]
#  - name: 'gcr.io/${PROJECT_ID}/terraform:0.12.8'
#    dir: './terraform/dns-zone'
#    args: [
#      'apply',
#      '-auto-approve',
#      '-var-file=input.tfvars'
#    ]
#    env:
#      - "TF_VAR_project=${_PROJECT_ID}"
#      - "TF_VAR_region=${_REGION}"
#      - "TF_VAR_dns-zone-name=${_DNS_ZONE_NAME}"
#      - "TF_VAR_domain-name=${_DOMAIN_NAME}"

  - name: 'gcr.io/${PROJECT_ID}/terraform:0.12.8'
    dir: './terraform'
    args: [
      'init',
      '-backend-config=bucket=${_PROJECT_ID}-gitlab'
    ]
  - name: 'gcr.io/${PROJECT_ID}/terraform:0.12.8'
    dir: './terraform'
    args: [
      'apply',
      '-auto-approve',
    ]
    env:
      - "TF_VAR_project=${_PROJECT_ID}"
      - "TF_VAR_region=${_REGION}"
      - "TF_VAR_dns-zone-name=${_DNS_ZONE_NAME}"
      - "TF_VAR_domain-name=${_DOMAIN_NAME}"
      - "TF_VAR_gke-cluster-version=${_CLUSTER_VERSION}"
      - "TF_VAR_letsencrypt-email=${_LETSENCRYPT_EMAIL}"
      - "TF_VAR_gitlab-chart-version=${_GITLAB_CHART_VERSION}"
    timeout: 1800s
substitutions:
  _REGION: "us-west1"
  _PROJECT_ID: "my-project"
  _DNS_ZONE_NAME: "example-com"
  _DOMAIN_NAME: "example.com"
  _LETSENCRYPT_EMAIL: "my-email@example.com"
  _CLUSTER_VERSION: "1.13.7-gke.24"
  _GITLAB_CHART_VERSION: "2.3.5"
timeout: 1860s